### ISSUE TITLE
Annotations

### ISSUE THREAD

**Issue by mburns02** [niche-tester/playwright-testrail-reporter#5]
Huge thank you for creating this. It has saved me loads of time!.

I have made a change locally which may benefit others. Rather than reading the case Id from the title I've changed it to read from an annotation so the test setup looks like

> test('dashboard-create @testrail', async ({ page, basePage }) => {
>          test.info().annotations.push({ type: 'Case Link', description: '28283510' });
> })

Just a different place to store the Id as we don't want to keep them in the test name.

**Comment by denisha** [comment]
thanks for this!
