### ISSUE TITLE
Failed to update test results

### ISSUE THREAD

**Issue by Azujual** [niche-tester/playwright-testrail-reporter#6]
Hello,
i'm trying to use your package and after some retries i was able to make it work, however it still fails to upload test results.
May i ask you assit me with this issue:
`[playwright-testrail-reporter] Updating test status for the following TestRail Run ID: 3
[playwright-testrail-reporter] Failed to update test results: {}`

**Comment by brandonyhchan** [comment]
Hey, I'm having the same issue. Were you able to resolve it? If so, what steps did you take? Thanks

**Comment by fertavora** [comment]
@Azujual did you have this issue? #7 
If yes, how did you solve it? 
I could not get to the "Updating test status" step yet...
Thanks in advance!

**Comment by inf0lio** [comment]
@denisha Hello! I have the same issue. Can you please help us with it?
`[playwright-testrail-reporter] Failed to update test results: {"name":"TestRailException"}`

**Comment by denisha** [comment]
thanks for the workaround @raymondfx 

@Azujual @fertavora this should now be fixed in [the latest release (v1.2.1)](https://github.com/niche-tester/playwright-testrail-reporter/releases/tag/v1.2.1)
