### ISSUE TITLE
Only Absolute URLs are supported 

### ISSUE THREAD

**Issue by brandonyhchan** [niche-tester/playwright-testrail-reporter#7]
Hi, trying to use your package to upload test results to testrail, and ran into this issue after adding all env variables
`[playwright-testrail-reporter] Failed to create new TestRail run: TypeError: Only absolute URLs are supported`
Would you have any idea why this is occurring? Any help would be appreciated

**Comment by fertavora** [comment]
I had the same problem.
Docs read:
`TESTRAIL_HOST: TestRail instance domain name e.g ```testrail.instance.io``` (exclude the https protocol)`

But I tried with and without `https://` and it failed on both tries.

**Comment by denisha** [comment]
apologies my documentation was incorrect, i have updated it 
But i also could not reproduce the issue you had with specifying https://

**Comment by anastasijabulatova-toast** [comment]
I have the same problem

**Comment by varjailic** [comment]
I'm still having same issue.

**Comment by exotlv** [comment]
@denisha  same problem. Any suggestions?
