### ISSUE TITLE
Failed to update test results because  unable to get local issuer certificate

### ISSUE THREAD

**Issue by fHirad** [niche-tester/playwright-testrail-reporter#8]
I got the following error while I'm trying to update the test result of an existing test case in an existing test run:

[playwright-testrail-reporter] TestRail Reporter has been initialised
[playwright-testrail-reporter] Existing Test Run with ID 5436 will be used
  ✓  1 [chromium] › RegE2E.spec.ts:5:5 › C35472: Login with valid credentials should succeed (24.6s)
btest1691601271301
[playwright-testrail-reporter] Test Case Completed : C35472: Login with valid credentials should succeed Status : passed
[playwright-testrail-reporter] Matched Test Case ID: 35472

  1 passed (26.2s)
[playwright-testrail-reporter] Updating test status for the following TestRail Run ID: 5436
[playwright-testrail-reporter] **Failed to update test results: {"message":"request to https://testrail/index.php?/api/v2/add_results_for_cases/5436 failed, reason: unable
to get local issuer certificate","type":"system","errno":"UNABLE_TO_GET_ISSUER_CERT_LOCALLY","code":"UNABLE_TO_GET_ISSUER_CERT_LOCALLY"}**

I tried followings and none of them helped so far:

1) npm config set registry http://registry.npmjs.org/
2)  npm config set strict-ssl false

 Any help will be greatly appreciated.

**Comment by denisha** [comment]
Hi @fHirad i noticed that the request is trying to use` https://testrail/index.php?/api/v2/add_results_for_cases/5436`
Can you confirm if you have specified the correct TestRail domain? 

for example it should be  `https://<name>.testrail.io`

**Comment by fHirad** [comment]
Thank you @denisha for your comment. 
The whole URL is mainly correct. I did a small modification in order not to expose my comany name due to the restricted policy. Basically the actual URL is
https://{companyName}testrail/index.php?/api/v2/add_results_for_cases/5436
{CompanyName} must be replaced with the actual value.
The rest is extaly from the logs

I know, the domain looks wierd but that is the way that they set it up
I can go to test rail / test run using Chrome or any other browser by using a similar URL like
https://{CompanyName}testrail/index.php?/runs/view/5436

**Comment by denisha** [comment]
ok got it, I will look into it and get back to you. I cannot reproduce this error on my end so not sure what could be the cause

**Comment by denisha** [comment]
@fHirad can you clarify that the testrail domain has no ".io" in the end ? is this how its setup in your company? I am not sure if this issue is related to my package. I have a feeling its probably related to the way testrail is being configured on the server.

**Comment by fHirad** [comment]
@denisha We don't have ,io in our domain.
We can reach testrail (the same server and setting) from Selenium. 
Only with playwright, I'm enountering the issue. So, I guess, if something was wrong with our setting, we should bot be able to connect to testrail from Seleniu.
