### ISSUE TITLE
Timed out tests are not reported 

### ISSUE THREAD

**Issue by sheinein-im** [niche-tester/playwright-testrail-reporter#9]
The issue is that in the status map in reporter.js, the string is **timeout** but the status in the logs is **timedout** 
<img width="416" alt="image" src="https://github.com/niche-tester/playwright-testrail-reporter/assets/108528481/b568c81d-d697-48c9-bc01-5327b19c2d9a">
<img width="314" alt="image" src="https://github.com/niche-tester/playwright-testrail-reporter/assets/108528481/5706c6bf-0b76-4d8d-b5ec-c3d9deb571e8">

Fix would be to change the map key to **timedout**

**Comment by denisha** [comment]
@sheinein-im thanks for picking this up, I will make a change and let you know once its released.

**Comment by denisha** [comment]
Fixed in release [v1.1.3](https://github.com/niche-tester/playwright-testrail-reporter/releases/tag/v1.1.3)
